import type { Metadata } from "next";
import { geistMono, geistSans } from "@/assets/fonts/fontProvider";
import "@/assets/css/global.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Link href="/" className="logo">
            <img src="/images/logo.svg" alt="" />
          </Link>
          <nav>
            <ul>
              <li>
                <Link href="#" className="header-link">
                  Goodies
                </Link>
              </li>
              <li>
                <Link href="#" className="header-link">
                  JsWorld
                </Link>
              </li>
              <li>
                <Link href="#" className="header-link">
                  PyFan
                </Link>
              </li>
              <li>
                <Link href="#" className="header-link">
                  Forums
                </Link>
              </li>
              <li>
                <Link href="#" className="header-link-icon center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    className="lucide lucide-github"
                  >
                    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
                    <path d="M9 18c-4.51 2-5-2-7-2" />
                  </svg>
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
